### PR TITLE
Agrarian Skies Flavour

### PR DESCRIPTION
**Pull request by MarMed**

### CODE REVIEW

**Comment by Raekye** [comment]
I was originally thinking to not delete/change the inode of `/home/mcuser/minecraft`, because the Minecraft server wrapper runs with that as the working directory, although I ended up installing that after these Minecraft scripts so it won't be a problem. You make a good point of not doing `rm -rf *`

Regardless, it may be better (portability/forwards compatibility) to do the downloads/extraction in a different folder, then copy them to the target. You can see the MCServer script does this:

```
cp -r /path/to/source/folder/. /path/to/dest/folder # trailing slash optional
```

Will copy everything inside the source folder (including dotfiles) into the destination folder (`cp -r a/* b/` doesn't do dotfiles)

Maybe it would be good if we designed all the scripts to be executable anywhere, and they'll setup everything for the current directory. This way, it can be useful for anyone. You can use `pwd` for the working directory (to avoid hardcoding `/home/mcuser/minecraft`); `TARGET_DIR=$(pwd)` (need to add your own trailing slash)

Those aren't important for now, but the script shouldn't change the world folder, since the Minecraft server wrapper expects the world to be in the `world/` folder (so `mv HomeMP world` instead of changing `level-name`)

Will leave this open if you want to try those changes. Otherwise I'm happy to merge. Thanks again!

**Comment by MarMed** [comment]
I wouldn't mind changing the scripts to run anywhere. What directory should be used as the source folder? Am I correct in thinking that the minecraft directory is empty before the script runs? When I make these changes I'll also rename the world folder.

**Comment by Raekye** [comment]
To make it run anywhere, just need to save the current directory at the start (e.g. `WD=$(pwd)`), and replace all references to `/home/mcuser/minecraft` with `$(WD)`. To be as flexible as possible, you shouldn't assume anything about what's in the folder, and only try to delete what you need to

I might be confusing/it might seem over kill, but as an example:
- you download `$AGRARIANSKIES_PACK` and `$AGRARIANSKIES_MAP`. If for some reason those already existed (maybe partial download), `wget` will add a suffix to those files instead of overwriting. So you need to `rm -f` them (idempotent in the sense you can rerun this script multiple times and you'll have the same working result)
- you unzip those two files, so any file names that will be unzipped you should be `rm -f`ed too
- you don't want to delete any extra files; they're not related, and I don't think there's a good reason to (maybe the user has them there for a reason)

Now the nice thing is if you do this inside a new folder, e.g. `/tmp/agrarian_skies/`, you know that folder will be empty, and `cp -r /tmp/agrarian_skies/. "$WD"` will copy everything over, overwriting files with the same name (e.g. a partial install from before), while ignoring unrelated files

So something like

```
#!/bin/bash
set -e
WD="$(pwd)"
cd /tmp
rm -rf agrarian_skies # make sure it's clean
mkdir agrarian_skies
# do your thing
cp -r . "$WD/" # or /tmp/agrarian_skies/. instead of just "."
cd .. # get out of the folder so you can delete it
rm -rf agrarian_skies
```

Sorry for the delays... I'm improving the tests today, and every time it takes me forever. Doesn't help that the tests take forever to run

**Comment by MarMed** [comment]
I think that all made sense to me. So to clarify if I do everything in the working directory and then copy it all the the target directory, I don't need to do anything to the target directory afterwards? Or should I instead of emptying the target directory completely I should remove every file and folder that will be copied from the working directory? Sorry if this was confusing, I'm slowly wrapping my head around the whole idempotency thing. No worry's about the delay, I spend most of the time on the computer so I respond pretty quickly. It helps that i'm really interested in Gamocosm XD. Also if you'd rather work on these scripts have at it, I wouldn't want you having to fix the mistakes I may make i'm far from an expert at this XD

**Comment by Raekye** [comment]
"So to clarify if I do everything in the working directory and then copy it all the the target directory" think you meant temporary directory instead of working directory :P (save the working directory at the beginning because you will `cd` to different directories. The original working directory is also the target directory at the end. We don't want to hardcode it to `/home/mcuser/minecraft` or anything)

No problem! Honestly I'm figuring out a lot as I go along too xD so it's nice working through it with someone

**Comment by Raekye** [comment]
Wow, looks awesome! The last thing I'm going to do is try to reach out to those pack developers and make sure they've got the thumbs up - shouldn't have a problem with this (setting up servers), but better get it right from the beginning than wish we had in hindsight

**Comment by MarMed** [comment]
In my opinion it should be fine, I'm not a lawyer though. I looked into it but couldn't find anything about distribution (although technically we aren't even distributing the modpacks) the modpack makers already received distribution permission when they created it. Of course it doesn't hurt to confirm with the pack devs. We will definitely have to ask ATLauncher packs for permission because we would have to store the packs at a more direct download friendly location. Also i'm slowly adding modpacks that I see that are popular but i'm bound to miss some. If in the wiki you could link to an issue or something for people to suggest modpacks that would be awesome. I also wanted to ask your opinion on the way I handled the RAM requirements?

**Comment by Raekye** [comment]
Yeah, I found Iskandar (crashlanding) and Jadedcat's (agrarian skies) twitters, but can't send direct messages unless they follow me (feel a little stupid tweeting the question xD ). You're right; I'm probably over thinking it. It's just a shell script on a public repository that downloads something from a public link for people

As for the RAM requirements, I think I'll expand the metadata to account for stuff like that, and website, authors, etc. It cool if I ask people to submit a (new) issue to suggest modpacks?

**Comment by MarMed** [comment]
Now that you mention it, if we credit the authors and link to their website that should be good, that's what most devs ask for. And I don't know why I didn't think of a new issue for modpack suggestions, that would work perfectly.

**Comment by Raekye** [comment]
Awesome, thanks again for the contribution!

**Pull request merged**
