### PR TITLE
Add TrueCraft script

### PR DESCRIPTION
**Pull request by ddevault**
http://truecraft.io

### CODE REVIEW

**Comment by Raekye** [comment]
I think you should add a "dnf -y install mono-core" since mono isn't installed by default. I'll test and confirm myself tomorrow evening that everything works smoothly if you haven't done so already. Otherwise, looks good - thanks!

**Comment by ddevault** [comment]
Pushed a fixed script. I went with `mono-complete` since I know that `mono-core` won't give us enough to run TrueCraft.

**Comment by Raekye** [comment]
I see there is `mono-complete` in ubuntu, but there's no equivalent in fedora (at a glance). However, I tried `mono-core` and it seemed to work, but I only connected with the vanilla b1.7.3 client and walked around and broke some blocks. I've never played beta myself so I'm not sure exactly what should be possible or not

I noticed I couldn't enter anything in the server console, I'm not sure if that's the way it is (never played/used beta myself). Using just `mono-core`, the console output had all these funny symbols

Next I tried the instructions on their website: http://www.mono-project.com/docs/getting-started/install/linux/ (after removing the `mono-core` installed)

```
rpm --import "http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF"
# next line updated for dnf in fedora 22
dnf config-manager --add-repo http://download.mono-project.com/repo/centos/
```

And installed `mono-complete` from their repo. Instead of the funny text I got colour output, but still no console input.

Lastly I tried (after uninstalling mono-complete) installing the native `mono-core` again, along with `mono-extras`. There's colour output

So at a glance, it seems `mono-core` and `mono-extras` fulfill the necessary requirements, but you may want to take a closer look. If everything is working as intended, I prefer using the native packages, but either way is cool.

Also, there should be an "install" in `dnf -y (install) mono-core (mono-extras)`. To show all mono packages, do `dnf search mono`. There were some additional packages for specific things (from visual basic to reflection to asp)

If you want me to spin you up a server to test/confirm everything is working just let me know

**Comment by ddevault** [comment]
Oh, my bad. We can run TrueCraft servers on `mono-core`, it's the client that needs `mono-complete`.

**Comment by ddevault** [comment]
Side note: we're working on this: https://github.com/SirCmpwn/TrueCraft/pull/150

**Comment by Raekye** [comment]
Should the server console be reading stuff/commands from stdin? If not then everything looks good (just wanted to confirm I wasn't missing anything causing it to glitch)

Query protocol would be awesome :D really cool project. I remember you used to do Craft.Net and was sad when you stopped. Didn't know you started this!

**Comment by ddevault** [comment]
No, it doesn't read commands from stdin. Eventually it might, but for now it does not.

Query protocol has been merged and is now working :smile:

**Comment by Raekye** [comment]
Awesome! Cool project and thanks for the submission :D

**Comment by ddevault** [comment]
:tada:

**Pull request merged**
